# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='last_updates',
            new_name='last_updated',
        ),
    ]
